# Generated by Django 3.2.5 on 2021-08-22 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0002_rename_desination_teacher_course'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='exam',
        ),
        migrations.AlterField(
            model_name='question',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='App_Login.teacher'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
