# Generated by Django 3.2.5 on 2021-08-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ques',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
