# Generated by Django 3.2.5 on 2021-08-22 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='desination',
            new_name='course',
        ),
    ]
